### ISSUE TITLE
Tag and deploy 1.0.0-beta

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#170]
I've filled in the [instructions for deploying profiles](http://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/technical/deployment/).

Once we're ready, we need to create a tagged release (`1__0__0__beta`) and then run the "Build and deploy" steps of those instructions.

* The "Copy the schema into place" step requires documentation, but it should be similar to the standard's instructions. The result should be the consolidated extension at http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/

* The "Update the deployment repository" step also has a TODO comment.

We also need to add the consolidated extension to the extension registry: https://github.com/open-contracting/extension_registry/issues/114

**Comment by Bjwebb** [comment]
FWIW `1__0__beta` would be more consistent with our OCDS standard releases (https://github.com/open-contracting/standard/releases - `1__0__RC`).

**Comment by jpmckinney** [comment]
The standard went from 1__0__RC to 1__0__0 (though in the changelog, it's 1.0.RC to 1.0). However, according to https://semver.org, release candidates (and beta, alpha, etc.) are labels on an otherwise full version number. So, I think it's better to stick with 1__0__0__beta, as I consider 1__0__RC to be a small error (not something to worry about).

**Comment by jpmckinney** [comment]
@duncandewhurst @Bjwebb I think we're ready to proceed with a tag and deploy.

Feel free to merge #179 and #180 as part of that.

**Comment by jpmckinney** [comment]
Noting that I'll fix the logic around the replacement of `{{version}}` and then update this issue.

Original issue was https://github.com/open-contracting/public-private-partnerships/issues/173

**Comment by jpmckinney** [comment]
#182 is merged. @kindly can continue with the deploy.

**Comment by kindly** [comment]
@jpmckinney 
I have a few concerns with the deploy as currently stands:

The place allotted for the full extension is currently http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/extension.json as [documented](http://standard.open-contracting.org/profiles/ppp/1.0/en/technical/#the-ocds-for-ppps-schema).  I am not sure I agree it should be there as it is not a schema but an extension.

There is a link to the full patched schema here: http://standard.open-contracting.org/profiles/ppp/1.0/en/_static/patched/release-schema.json
The full patched schema should really have its `id` as the canonical url of where that schema lives.
Currently the `id` is `http://standard.open-contracting.org/schema/1__1__3/release-schema.json`, this will cause problems for validators as they will look in that url when `$ref` resolving (even internal refs) causing issues.

Also, we need a place for the zipped version of the full profile so we add it to the extension registry.

My suggestion for this would be:

- Use the `schema` directory for the fully applied release-schema.json i.e http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/release-schema.json using this in the `id` field too.
  - We would need the correct `id` in this case so would need the compiling script to be updated with a special case for a real release. 
- Use an `extension` directory for the fully applied release-schema.json i.e http://standard.open-contracting.org/profiles/ppp/extension/1__0__0__beta/extension.json (and other files that normally live in the extension - release-schema.json and codelist directory).
- Have http://standard.open-contracting.org/profiles/ppp/extension/1__0__0__beta.zip as the zipped official version.

**Comment by duncandewhurst** [comment]
thanks @kindly I think this makes sense to get right now and is good learning for future profile deploys

**Comment by jpmckinney** [comment]
@kindly Your suggestions sound good to me. Are these actions you can take forward? I think the steps are:

* Provide the `id` in [`build-profile.py`](https://github.com/open-contracting/public-private-partnerships/blob/1.0-dev/schema/build-profile.py#L14) as an argument to the [`build_profile`](https://github.com/open-contracting/documentation-support/blob/master/ocdsdocumentationsupport/__init__.py#L57) method, which can pass it to [`ProfileBuilder.patched_release_schema()`](https://github.com/open-contracting/documentation-support/blob/master/ocdsdocumentationsupport/profile_builder.py#L62)
* Update deploy process to:
  * Copy `schema/patched` to `schema/1__0__0__beta` (i.e. patched release-schema.json and patched codelists)
  * Copy `schema/profile` to `extension/1__0__0__beta` (i.e. `extensions.json`, consolidated release-schema.json and consolidated codelists)
  * Create a ZIP archive of `extension/1__0__0__beta` and put it at `extension/1__0__0__beta.zip` (within the ZIP file, I figure the paths would be e.g. `1__0__0__beta/extension.json`)

**Comment by kindly** [comment]
@jpmckinney 
Yes those are the actions and I can take them forward. We also need to:

- Update the docs and examples to reflect the url changes.
