### ISSUE TITLE
milestoneType and milestoneCode codelists missing from documentation

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#186]
The [milestoneType codelist](https://github.com/open-contracting/public-private-partnerships/blob/1.0-dev/schema/patched/codelists/milestoneType.csv) is missing from the [codelists page](http://standard.open-contracting.org/profiles/ppp/latest/en/reference/codelists/#codelists) of the documentation.

The [schema reference](http://standard.open-contracting.org/profiles/ppp/latest/en/reference/schema/) currently links to the milestoneType codelist in OCDS core - this should be updated once the codelist appears in the PPP extension.

The [milestoneCode codelist](https://github.com/open-contracting/public-private-partnerships/blob/1.0-dev/schema/patched/codelists/milestoneCode.csv) is missing from the codelists page of the documentation.

The schema reference for `milestone/code` doesn't currently link to the milestoneCode codelist - this should be updated once the codelist appears in the PPP extension.

**Comment by jpmckinney** [comment]
Changing the URL would require changing the `description` field (through the PPP extension). Is that the intention? We typically don't change titles or descriptions of fields in extensions.

An alternative is for the `build-profile.py` script to find and replace URLs. At least that way, if the standard updates its description, the profile will use it in its patched schema, without having to remember to change the PPP extension. We might want to apply this strategy to all codelists modified by the profile.

**Comment by duncandewhurst** [comment]
Agree we shouldn't change the description in the PPP extension.

The alternative proposal sounds good and I think applying it to all codelists in the profile would be preferable, since even where codelists are not extended by the profile, they have an entry on the [codelist reference page](http://standard.open-contracting.org/profiles/ppp/latest/en/reference/codelists/).

The only disadvantage I see to updating the URLs is that there is extra contextual information about some codelists in the codelist reference page in the core documentation which doesn't appear in the codelist reference page in the PPP profile.

**Comment by jpmckinney** [comment]
We can perhaps add a link to the core docs from the profile for the extra information.

Also, if a codelist isn't modified by the profile (like currency, for example), should we instead not have any information on the reference page at all, and just provide a link to the core docs for that codelist?

**Comment by duncandewhurst** [comment]
Sounds good to me.

**Comment by jpmckinney** [comment]
Copying my comment from #188: These issues suggest that perhaps URLs should be stored outside descriptions – to avoid having to manipulate normative content when changing URLs.

**Comment by duncandewhurst** [comment]
@jpmckinney, just checking we're on the same page with what needs to be done here:

1. Add the milestoneType and milestoneCode codelists to the codelist reference page
2. Remove codelists which are not modified by the profile from the codelist reference page and add a section with links to the unmodified codelists in the OCDS documentation (same [approach as OC4IDS](http://standard.open-contracting.org/infrastructure/latest/en/reference/codelists/#ocds-codelists))
3. Update `build-profile.py` to find and replace URLs for codelists which are modified by the profile, to reference the codelist reference page in the profile, rather than the OCDS docs
4. Add a note to the top of codelist reference page with a link, explaining that there is extra contextual information about some codelists in the OCDS docs

**Comment by jpmckinney** [comment]
For (2), please put the references at the top of the page, before the codelists. As a documentation user, I find that I assume the structure of the page is codelist names followed by tables; I wouldn't expect to look for or find a list of links at the bottom of the long page. An issue can be created for OC4IDS.

I can do (3) once the others are done.

For (4), wouldn't it be better to put that note for each relevant codelist? Many links jump directly to the codelist entry on the page, and users are less likely to scroll up to see that notice.

**Comment by jpmckinney** [comment]
Moved build-profile.py task to #215
