### ISSUE TITLE
Mysterious milestones extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#194]
http://standard.open-contracting.org/profiles/ppp/latest/en/extensions/milestones/

Linked from http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#i-10-project-approval-dates

@duncandewhurst I don't understand this page, as these `milestones` fields are part of core, and there is no extension to which this documentation relates.

**Comment by duncandewhurst** [comment]
Most of the changes in the draft extension documented on http://standard.open-contracting.org/profiles/ppp/latest/en/extensions/milestones/ ended up being added to core as part of the 1.1 upgrade.

The changes which aren't in core (additions to the milestoneType codelist and adding a codelist for milestoneCode) are actually part of the [PPP extension](https://extensions.open-contracting.org/en/extensions/ppp/master/) and are documented there, so I think this page can be removed and the link from the framework reference replaced with a link to the milestones reference in the main OCDS docs.

Alternatively, the page could be moved under the 'Schema Reference' section of the documentation, with appropriate updates to the language.

**Comment by jpmckinney** [comment]
Okay, I went with removing the page in #206
