### ISSUE TITLE
Please add me as a maintainer on ocds-for-ppps.readthedocs.io

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#196]
I need to turn off search engine indexing, and fix redirection on branches like https://ocds-for-ppps.readthedocs.io/en/stable/extensions/ppp/

Not sure who has access so tagging @Bjwebb @robredpath @duncandewhurst @kindly

**Comment by duncandewhurst** [comment]
Is your readthedocs username also jpmckinney?

**Comment by robredpath** [comment]
I've added @duncandewhurst and @jpmckinney as maintainers to that project.

**Comment by jpmckinney** [comment]
Thanks, @robredpath. Can you please also add us to https://readthedocs.org/projects/ocds-for-ppps-spanish/ ?

**Comment by robredpath** [comment]
@jpmckinney done!

**Comment by jpmckinney** [comment]
Redirection now working on /es/ of ReadTheDocs:

https://ocds-for-ppps.readthedocs.io/es/stable/
https://ocds-for-ppps.readthedocs.io/es/latest/
