### ISSUE TITLE
Create new codes instead of changing semantics of existing codes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#197]
Originally discussed in https://github.com/open-contracting/infrastructure/pull/75#issuecomment-458990276

Code | PPP Title | PPP Description | OCDS Title (if different) | OCDS Description (if different)
-- | -- | -- | -- | --
needsAssessment | Needs Assessment | Information on the project need, benefits provided, and economic and social impact |   | Documentation of the needs assessments carried out for this contracting process addressing demand for the project or investment from the affected communities or users.
contractSchedule | Schedules and milestones | Documentation setting out key milestones and schedules. Structured versions of this information may be modelled using the milestones block. | Contract schedules | Any document which contains additional terms, obligations or information related to the contract, such as a schedule, appendix, annex, attachment or addendum.

The semantics of `needsAssessment` are changed from being about the contracting process to being about the project. The semantics of `contractSchedule` are changed from being about "contract schedules" in a legal sense (annexes, etc.) to being about schedules in a time sense (milestones, etc.).

For `needsAssessment`, I think we should either change the description to be agnostic to what it is describing ("the contracting process or project" or "the object this document is about"), or create a new code.

For `contractSchedule`, the PPPs profile should create a new code, rather than changing semantics.

**Comment by jpmckinney** [comment]
Noting we should align the definition of `environmentalImpact` between PPP and Infra codelists.

**Comment by duncandewhurst** [comment]
The element of the PPP framework which the `needsAssessment` code is used to meet is phrased as follows:

> Project need: benefits provided, economic and social (including specific information on the public interest aspect)

i.e. the economic and social benefits are considered part of the project need, so I think it's fine to use the expanded definition of `needsAssessment` from OC4IDS:

> Documentation of the needs assessments carried out for this contracting process or project addressing demand for the project or investment from the affected communities or users.

For `contractSchedule` we can rename the code to `contractMilestones` and use the existing description.

I've drafted PR #205 with the above changes, plus updating `environmentalImpact` to use the definition from OC4IDS.

**Comment by jpmckinney** [comment]
Sounds good – so we're effectively adding "or project" to the OCDS definition of `needsAssessment`, which was one option discussed in open-contracting/infrastructure#75.
