### ISSUE TITLE
Add guidance on publishing subcontracting information

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#200]
See https://github.com/open-contracting/standard/issues/392#issuecomment-458378759

**Comment by jpmckinney** [comment]
Do we need guidance on subcontractors in three places? I'd rather have it in one place and use links. If there's something unique to PPPs, we can have that unique content here, and then link to the rest.

**Comment by jpmckinney** [comment]
Closing in favor of open-contracting/standard#392.
