### ISSUE TITLE
Sample data: Remove planning.budget.amount

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#208]
`planning.budget.amount` is populated in the sample data, however this field is not referenced in the [framework reference](https://github.com/open-contracting-extensions/ocds_budget_breakdown_extension#guidance) and instead `planning.project.totalValue` is recommended to provide the planned value of the project.

Recommend removing `planning.budget.amount` as it is unclear whether this relates to the the total value of the project or just the funds from the public authority.

cc @pindec

**Comment by jpmckinney** [comment]
Framework reference is here (link above is to budget breakdown extension): http://standard.open-contracting.org/profiles/ppp/latest/en/framework/

I rolled this into #203. See new note in readme in that PR: we should edit the examples in the `ocds-show` repository (where these examples come from) not in this repo, as changes will be overwritten by `make update_ocds_show`.

**Comment by duncandewhurst** [comment]
Closed by #203
