### ISSUE TITLE
Use GitHub Pages deployment of OCDS Show for PPPs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#211]
In a recent pull request, I spent a fair amount of time reconciling differences between the ocds-show-ppp repository, and the edited version of it that is stored in this repo.

Instead of embedding ocds-show-ppp in this repo, we should just use the live version at https://open-contracting.github.io/ocds-show-ppp/

On http://standard.open-contracting.org/profiles/ppp/latest/en/example/#explore-the-example, instead of a link like:

    ../_static/ocds-show/?load=../full_record_package.json

It would be:

    https://open-contracting.github.io/ocds-show-ppp/?load=https://standard.open-contracting.org/profiles/ppp/latest/en/_static/full_record_package.json

* [x] Set CORS headers on standard documentation server
* [x] Update links to local copy of ocds-show to use remote service
* [x] Delete local copy of ocds-show
* [x] Update `update_ocds_show` make command (trim it down to update `docs/examples` by `curl`'ing the two files from the ocds-show-ppp repository)
* [x] Update reference to ocds-show in readme

**Comment by jpmckinney** [comment]
See https://github.com/open-contracting-extensions/public-private-partnerships/pull/209#discussion_r307908393 for implementation details and rationale.

**Comment by duncandewhurst** [comment]
This will be easier for one of the devs to do than for me so I've created a [Trello card](https://trello.com/c/U9Zhzy12/50-ocds-for-ppps-use-github-pages-deployment-of-ocds-show-for-ppps#) to discuss on the next portfolio call.

**Comment by jpmckinney** [comment]
I just need ODS to set the CORS headers, as I don't know how to do that in our deployment system (and I don't think I can without write access to opendataservices-deploy). It'll be quick for me to do the rest as I already know exactly what to do.

**Comment by duncandewhurst** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set CORS headers on standard documentation server](https://trello.com/c/U9Zhzy12/50-set-cors-headers-on-standard-documentation-server)

**Comment by Bjwebb** [comment]
We should set this header in the [Apache config](https://github.com/open-contracting/deploy/blob/master/salt/apache/ocds-docs-live.conf.include):

```
Access-Control-Allow-Origin: *
```

This header must appear for all JSON files, but shouldn't appear for data review tool pages, to avoid possible future XSS attacks.

**Comment by Bjwebb** [comment]
CORS headers are now set on the documentation servers - https://github.com/open-contracting/deploy/commit/3f361435bb6ee8e3a82a5c5a8de7b10070910398

The GitHub pages link now works - https://open-contracting.github.io/ocds-show-ppp/?load=https://standard.open-contracting.org/profiles/ppp/latest/en/_static/full_record_package.json
