### ISSUE TITLE
Clearly state the relationship between a PPP and contracting process

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#216]
My understanding is that there is a one-to-one correspondence between the public-private partnership and a contracting process, and the documentation seems consistent with this, but I couldn't find where this was clearly stated.

**Comment by duncandewhurst** [comment]
Yes, that's correct.

I've added this to the technical overview page, which already describes the relationship between OCDS for PPPs and OCDS, in https://github.com/open-contracting-extensions/public-private-partnerships/pull/222
