### ISSUE TITLE
Restore buyer and suppliers fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#236]
These are renamed to publicAuthority and preferredBidders. This makes OCDS for PPPs data unnecessarily incompatible with OCDS data. The original terms are inappropriate, but this needs to be fixed in an OCDS 2.0, not in a profile. For OCDS 1.2, the fix is to broaden the definitions of buyer and suppliers, while retaining the terms.

**Comment by jpmckinney** [comment]
cc @duncandewhurst

**Comment by duncandewhurst** [comment]
Agreed, sounds good.

**Comment by jpmckinney** [comment]
@duncandewhurst Since OCDS for PPPs is relevant to a few active implementers, and since you might be making changes to close #238, could you take on this issue, #237 and ideally #217 ?

**Comment by duncandewhurst** [comment]
Sure, should I prioritise those above 1.2 issues?

**Comment by jpmckinney** [comment]
Yes, looks like Matt, Kadie and Charlie have taken on enough 1.2 issues for now.

**Comment by duncandewhurst** [comment]
@jpmckinney a couple of questions on your preferred approach:

* Should we remove `publicAuthority` and `preferredBidders` completely, or should we deprecate them?

* Should we also remove/restore the associated codes in `partyRole.csv`?

**Comment by jpmckinney** [comment]
> Should we remove publicAuthority and preferredBidders completely, or should we deprecate them?

Since the profile isn't 1.0 but is beta, I think better to remove.

> Should we also remove/restore the associated codes in partyRole.csv?

Yes, good catch.
