### ISSUE TITLE
Remove initiationType.csv

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#237]
Related: https://github.com/open-contracting/standard/issues/821

**Comment by jpmckinney** [comment]
cc @duncandewhurst

**Comment by duncandewhurst** [comment]
I'm happy with this, per https://github.com/open-contracting/standard/issues/821#issuecomment-734019550

**Comment by duncandewhurst** [comment]
@jpmckinney SIF SOURCE's data includes a boolean `isPPP/Concession` field. In the absence of setting `initiationType` to 'ppp', how would you recommend mapping this field?

**Comment by jpmckinney** [comment]
What are the semantics of that field and to what object would it relate?

**Comment by duncandewhurst** [comment]
The field is in the projects table in the SOURCE database, it hasn't been mapped to OCDS yet.

I only know the field name and type, but I'm assuming the semantics are:

* If the field is set to `true`, then the project/contracting process is a PPP or a concession.
* If the field is set to `false`, then the project/contracting process is not a PPP or a concession.

Note that there is a 1:1 relationship between a project and a contracting process in SOURCE.

**Comment by jpmckinney** [comment]
At present, there is no field for this "type" information. We should open an issue on the standard to discuss how to disclose this information.

For example, the EU's standard procurement forms include separate sets of forms for utilities, design contests, concessions, transport, and "social and other specific services", but this type isn't expressed in data fields (and thus is not expressed in the OCDS mapping) – except indirectly via the use of particular fields in OCDS (or in the notice type/form name in the EU). Note that, in eForms (the EU's future forms), the same forms are used for different types, and a notice type field is used instead.

In other systems, this type information is disclosed indirectly through `procurementMethodDetails`, since some procedures are exclusively used for specific types.

For SOURCE, `isPPP/Concession` sounds like something a software developer came up with, so it isn't a great start for clear semantics. We should clarify what information it is trying to relate, so that we can model it correctly.

**Comment by duncandewhurst** [comment]
SIF clarified that the semantics are as expected:

> Whether the project intended to be tendered as a PPP/Concession or as a traditional procurement
