### ISSUE TITLE
Update history and governance page

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#239]
The intro to the history and governance page is out of sync with the [Partners](https://standard.open-contracting.org/profiles/ppp/latest/en/#partners) section of the homepage.

If I remember correctly, we were asked to update the latter by the World Bank, so we should update the history and governance to match.

**Comment by jpmckinney** [comment]
Alternately, we can remove the duplication, and rename the page to Governance.
