### ISSUE TITLE
Restore removed party roles

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#249]
The ppp extension removes 'procuringEntity', 'tenderer' and 'funder': https://github.com/open-contracting-extensions/ocds_ppp_extension/blob/master/codelists/-partyRole.csv

It looks like it adds 'bidder' to replace 'tenderer', and more specific roles to replace 'funder': https://github.com/open-contracting-extensions/ocds_ppp_extension/blob/master/codelists/%2BpartyRole.csv

I don't know why 'procuringEntity' is removed. It's used in the example.

I propose restoring all codes. It's no problem for there to be a more generic 'funder' role alongside more specific roles (note: there is discussion of its deprecation, see https://github.com/open-contracting/standard/issues/825), and this profile should probably use 'tenderer' instead of 'bidder'. If a change to that code's description is needed, an issue can be opened on the `standard` repository.

**Comment by duncandewhurst** [comment]
Once https://github.com/open-contracting-extensions/ocds_ppp_extension/pull/13 is merged I'll run `build_profile.py` to pull in the changes.
