### ISSUE TITLE
Add codes to documentType.csv, instead of replacing it

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#253]
https://github.com/open-contracting-extensions/ocds_ppp_extension/blob/master/codelists/documentType.csv

This contains codes from OCDS, other extensions, etc. It is a maintenance challenge, since any improvements, corrections or deprecations of those codes in OCDS and extensions will not be reflected here.

For example, in OCDS the description of 'contractSchedule' had drifted toward 'contractAnnexe', such that 'contractSchedule' is deprecated: https://github.com/open-contracting/standard/issues/870

Instead of replacing the codelist, the PPP extension should only add the codes that are unique to that extension.

**Comment by jpmckinney** [comment]
FYI @ColinMaudry

**Comment by duncandewhurst** [comment]
Once we've merged https://github.com/open-contracting-extensions/ocds_ppp_extension/pull/15 then we need to run `build_profile.py` to close this issue.

**Comment by jpmckinney** [comment]
I ran `make clean_dist` first, to clear out old files (`documentType.csv` and `-partyRole.csv`). #262
