### ISSUE TITLE
Remove quote in the first stage section of the framework reference

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting-extensions/public-private-partnerships#272]
The quote under the [first stage heading](https://standard.open-contracting.org/profiles/ppp/latest/en/framework/#ii-1-first-stage) reads:

> The act of testing prospective bidders to determine whether they meet the pass/fail qualification criteria in advance of issuing the request for proposals.

Which seems contradictory of the description on the following line:

> Use the tender section to describe the first stage of the contracting process, whether it involves the submission of bids, or requests to participate.

**Comment by jpmckinney** [comment]
Is it contradictory? The quote assumes that there is a two-stage process. The description allows for a single-stage process. I think we maybe need to re-word to address the ambiguity.

**Comment by duncandewhurst** [comment]
Hmm - I read 'in advance of issuing the request for proposals' as excluding requesting proposals in the first stage.

In any case, the quote is the definition of 'pre-qualification' from https://ppp-certification.com/ppp-certification-guide/glossary so I don't think it really makes sense to feature it as the definition of 'first stage'.

I think we should remove the quote and reword the description to include 'pre-qualification', e.g.

> Use the tender section to describe the first stage of the contracting process, whether it involves the submission of bids (as in a single-stage process), or requests to participate (as in a two-stage process with pre-qualification).

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by jpmckinney** [comment]
closed by c8fffd8
