### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/public-private-partnerships#275]
OCDS for PPPs was removed from Transifex as it changes infrequently.

Manually search for `msgstr ""\n\n` in (10 occurrences total):

* [x] spreadsheet.po
* [x] framework.po
* [x] changelog.po
* [x] codelists.po

ppp-schema.po and ppp-codelists.po can be updated by first [translating extensions](https://github.com/open-contracting/ocds-extensions-translations#ocds-extensions-translations), and then running https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/translation.html

**Comment by jpmckinney** [comment]
Assigned @yolile when you have time.

**Comment by yolile** [comment]
I've created a PR for the manual translations but will keep this issue open until ppp-schema.po and ppp-codelists.po are also translated

**Comment by yolile** [comment]
> ppp-schema.po and ppp-codelists.po can be updated

For doing this, should I create new resources, e.g. ppp--1_0 or the existing master ones are fine?

**Comment by jpmckinney** [comment]
Keep master. We'll only need 1.0 if we ever create a 1.1 (unlikely).

**Comment by jpmckinney** [comment]
Ah, just noticed ppp extension was split from master into 1.1 and 1.2, so I'll need to create and delete resources.

**Comment by yolile** [comment]
I've translated `ppp-master-schema` and `ppp-master-docs` in Transifex now

**Comment by jpmckinney** [comment]
The remaining extensions to translate are (you can just do --schema and --codelists, not --docs):

* [x] charges
* [x] documentation_details
* [x] finance
* [x] metrics
* [x] performance_failures
* [x] project
* [x] risk_allocation
* [x] shareholders
* [x] signatories
* [x] tariffs

There should only be about 68 strings across all these.

**Comment by yolile** [comment]
All done now

**Comment by jpmckinney** [comment]
Cool, I did the rest of https://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/translation.html and just needed to copy over two translations from Transifex manually, because the profile rewrites some URLs, causing a difference with the source string on Transifex.
